name: Submit to TestFlight

on:
  workflow_dispatch:
    inputs:
      build_id:
        description: 'Build ID to submit (leave empty for latest)'
        required: false
        default: ''

jobs:
  submit:
    name: Submit to TestFlight
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Debug EAS Project Info
        run: |
          echo "=== EAS User Info ==="
          eas whoami || echo "Not logged in"
          echo "=== Project Info ==="
          eas project:info --non-interactive || echo "No project found"
          echo "=== Recent Builds ==="  
          eas build:list --limit=3 --json --non-interactive || echo "No builds found"

      - name: Submit to TestFlight
        run: |
          if [ -n "${{ inputs.build_id }}" ]; then
            eas submit --platform ios --id ${{ inputs.build_id }} --non-interactive
          else
            eas submit --platform ios --latest --non-interactive
          fi